package edu.orangecoastcollege.cs272.capstone.view;

import javafx.fxml.FXML;

import javafx.scene.control.TextField;
import javafx.stage.Stage;
import edu.orangecoastcollege.cs272.capstone.controller.Controller;
import edu.orangecoastcollege.cs272.capstone.model.Customer;
import javafx.application.Application;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CustomerScene {
	
	private Controller controller = Controller.getInstance();
	
	@FXML
	private TextField PlasticTF;
	@FXML
	private TextField AluminumTF;
	@FXML
	private TextField GlassTF;
	@FXML
	private Label PlasticAmountLabel;
	@FXML
	private Label AluminumAmountLabel;
	@FXML
	private Label GlassAmountLabel;
	@FXML
	private Label TotalAmountLabel;
	@FXML
	private Label UserLabel;
	@FXML
	private Label PlasticErrorLabel;
	@FXML
	private Label AluminumErrorLabel;
	@FXML
	private Label GlassErrorLabel;
	@FXML
	private Label TotalErrorLabel;
	@FXML
	private Label MaterialsLabel;
	
	@FXML
    void initialize() {
		
		UserLabel.setText(controller.mCurrentCustomer.getmUser());

    }
	
	// Event Listener on Button.onAction
	@FXML
	public void DonationsChart(ActionEvent event) {
		// TODO Autogenerated
		 
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void LogOut(ActionEvent event) {
		// TODO Autogenerated
		
		ViewNavigator.loadScene("Welcome to OCC Recycling Center", ViewNavigator.FIRST_SCENE);
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public boolean Calculate(ActionEvent event) {
		
		PlasticErrorLabel.setVisible(PlasticTF.getText().isEmpty());
		AluminumErrorLabel.setVisible(AluminumTF.getText().isEmpty());
		GlassErrorLabel.setVisible(GlassTF.getText().isEmpty());
		
		if(PlasticErrorLabel.isVisible() || AluminumErrorLabel.isVisible() || GlassErrorLabel.isVisible())
			return false;
		
		double plastic = Double.parseDouble(PlasticTF.getText());
		double aluminum = Double.parseDouble(AluminumTF.getText());
		double glass = Double.parseDouble(GlassTF.getText());
		
		double total1 = plastic + aluminum + glass;
		
		double plasticMoney = plastic * 5;
		double aluminumMoney = aluminum * 5;
		double glassMoney = glass * 5;
		double total2 = plasticMoney + aluminumMoney + glassMoney;
		
		String p = String.valueOf(plasticMoney);
		String a = String.valueOf(aluminumMoney);
		String g = String.valueOf(glassMoney);
		String t1 = String.valueOf(total1);
		String t2 = String.valueOf(total2);
		
		MaterialsLabel.setText(t1 + " materials");
		
		PlasticAmountLabel.setText(p + " cent");
		AluminumAmountLabel.setText(a + " cent");
		GlassAmountLabel.setText(g + " cent");
		TotalAmountLabel.setText(t2 + " cent");
		
		String user = UserLabel.getText();
		
		int id = controller.mCurrentCustomer.getmId();
		
		controller.recordCustomer(id, plastic, aluminum, glass, total2);
		
		return true;
		
	}
	
	// Event Listener on Button.onAction
	@FXML
	public void Clear(ActionEvent event) {
		
		PlasticTF.setText("");
		AluminumTF.setText("");
		GlassTF.setText("");
		MaterialsLabel.setText("0 Materials");
		
		PlasticAmountLabel.setText(0 + " cent");
		AluminumAmountLabel.setText(0 + " cent");
		GlassAmountLabel.setText(0 + " cent");
		TotalAmountLabel.setText(0 + " cent");
		
	}
}
