package edu.orangecoastcollege.cs272.capstone.view;

import javafx.fxml.FXML;
import edu.orangecoastcollege.cs272.capstone.controller.Controller;
import javafx.event.ActionEvent;

import javafx.scene.control.Label;

public class CustomerInfoScene {

    Controller controller = Controller.getInstance();

	@FXML
	private Label FullLabel;
	@FXML
	private Label UserLabel;
	@FXML
	private Label EmailLabel;
	@FXML
	private Label PasswordLabel;
	@FXML
	private Label PlasticLabel;
	@FXML
	private Label AluminumLabel;
	@FXML
	private Label GlassLabel;
	@FXML
	private Label MoneyLabel;

	@FXML
    void initialize() {

	    FullLabel.setText(controller.mCurrentCustomer.getmName());
        UserLabel.setText(controller.mCurrentCustomer.getmUser());
        EmailLabel.setText(controller.mCurrentCustomer.getmEmail());
        PasswordLabel.setText(controller.mCurrentCustomer.getmPassword());
        PlasticLabel.setText(controller.mCurrentRecord.getPlastic() + " units");
        AluminumLabel.setText(controller.mCurrentRecord.getAluminum() + " units");
        GlassLabel.setText(controller.mCurrentRecord.getGlass() + " units");
        MoneyLabel.setText(controller.mCurrentRecord.getMoney() + " cents");

    }

	// Event Listener on Button.onAction
	@FXML
	public void Back(ActionEvent event) {
		// TODO Autogenerated

	    ViewNavigator.loadScene("Welcome to OCC Recycling Center", ViewNavigator.CUSTOMER_SCENE);

	}
}
